using System;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace UnityPuerExec
{
    public static class UnityPuerExecCompileCompatBridge
    {
        // Transitional bridge entry retained during T1.2.1 migration.
        public static void TriggerValidationCompile(string jobId, string marker)
        {
            var effectiveMarker = string.IsNullOrEmpty(marker) ? jobId : marker;
            UnityPuerExecCompileCompat.TriggerValidationCompile(effectiveMarker);
        }
    }

    internal static class UnityPuerExecCompileCompat
    {
        private const string CompileTriggerDirectory = "__UnityPuerExec__";
        private const string CompileTriggerFileName = "CompileTrigger.cs";

        [MenuItem("Tools/Unity Puer Exec/Trigger Package Compile")]
        private static void TriggerValidationCompileMenu()
        {
            TriggerValidationCompile("menu-" + DateTime.UtcNow.Ticks);
        }

        // Transitional compile-trigger entry retained during T1.2.1 migration.
        // Kept outside the primary server implementation so compatibility logic
        // does not read like part of the main runtime surface.
        internal static void TriggerValidationCompile(string marker)
        {
            var assetsRoot = Application.dataPath;
            var directory = Path.Combine(assetsRoot, CompileTriggerDirectory);
            Directory.CreateDirectory(directory);

            var filePath = Path.Combine(directory, CompileTriggerFileName);
            var className = "UnityPuerExecCompileTrigger";
            var content = $@"// Auto-generated by unity-puer-exec.
namespace UnityPuerExec.Generated
{{
    internal static class {className}
    {{
        internal const string Marker = ""{EscapeForCSharpLiteral(marker)}"";
    }}
}}";

            File.WriteAllText(filePath, content, Encoding.UTF8);
            Debug.Log($"[UnityPuerExec] Trigger compile marker={marker}");
            AssetDatabase.Refresh();
        }

        private static string EscapeForCSharpLiteral(string value)
        {
            if (string.IsNullOrEmpty(value))
            {
                return string.Empty;
            }

            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
